import { Question } from './types';

export const QUESTIONS_15: Question[] = [
  { id: 1, text: "我是一个爱交际、话多的人。", scorings: [{ dimension: 'extraversion', reverse: false }] },
  { id: 2, text: "我倾向于指出别人的错处。", scorings: [{ dimension: 'agreeableness', reverse: true }] },
  { id: 3, text: "我做事彻底。", scorings: [{ dimension: 'conscientiousness', reverse: false }] },
  { id: 4, text: "我经常感到忧郁。", scorings: [{ dimension: 'neuroticism', reverse: false }] },
  { id: 5, text: "我对艺术不感兴趣。", scorings: [{ dimension: 'openness', reverse: true }] },
  { id: 6, text: "我性格温和，容易相信别人。", scorings: [{ dimension: 'agreeableness', reverse: false }] },
  { id: 7, text: "我比较懒。", scorings: [{ dimension: 'conscientiousness', reverse: true }] },
  { id: 8, text: "我性格开朗，乐观。", scorings: [{ dimension: 'extraversion', reverse: false }] },
  { id: 9, text: "我经常感到紧张。", scorings: [{ dimension: 'neuroticism', reverse: false }] },
  { id: 10, text: "我喜欢思考，有很多想法。", scorings: [{ dimension: 'openness', reverse: false }] },
  { id: 11, text: "我经常丢三落四。", scorings: [{ dimension: 'conscientiousness', reverse: true }] },
  { id: 12, text: "我比较害羞，在人多的地方会感到不自在。", scorings: [{ dimension: 'extraversion', reverse: true }] },
  { id: 13, text: "我待人宽厚，不记仇。", scorings: [{ dimension: 'agreeableness', reverse: false }] },
  { id: 14, text: "我做事经常半途而废。", scorings: [{ dimension: 'conscientiousness', reverse: true }] },
  { id: 15, text: "我情绪稳定，不容易激动。", scorings: [{ dimension: 'neuroticism', reverse: true }] },
];

export const QUESTIONS_118: Question[] = [
  { id: 1, text: '我常常不知不觉就浪费了大把时间。', scorings: [{ dimension: 'conscientiousness', subDimension: 'C5', reverse: true }] },
  { id: 2, text: '我常常为还未发生的事情感到隐隐不安，比如在夜深人静时，脑海里会浮现各种“万一……怎么办”的念头。', scorings: [{ dimension: 'neuroticism', subDimension: 'N1', reverse: false }] },
  { id: 3, text: '我总能从平凡的事物中发现美好，比如夕阳下的云彩、路边盛开的小花，都能让我心情愉悦。', scorings: [{ dimension: 'openness', subDimension: 'O2', reverse: false }] },
  { id: 4, text: '我觉得主动靠近陌生人、开启一段对话是一件相当困难、令我不适的事。', scorings: [{ dimension: 'extraversion', subDimension: 'E2', reverse: true }] },
  { id: 5, text: '我在面对重要事件时，容易过度紧张、慌张，甚至导致发挥失常。', scorings: [{ dimension: 'neuroticism', subDimension: 'N6', reverse: false }] },
  { id: 6, text: '我习惯听从别人的安排，而不是主动出头，让做什么就做什么。', scorings: [{ dimension: 'extraversion', subDimension: 'E3', reverse: true }] },
  { id: 7, text: '我总能看到生活中积极的一面，哪怕阴天，也觉得云很美。', scorings: [{ dimension: 'extraversion', subDimension: 'E6', reverse: false }] },
  { id: 8, text: '我每次开始一项任务都很艰难，总要拖到最后一刻才动手。', scorings: [{ dimension: 'conscientiousness', subDimension: 'C5', reverse: true }] },
  { id: 9, text: '我一旦认定某件事，就很难被说服改变。', scorings: [{ dimension: 'agreeableness', subDimension: 'A4', reverse: true }] },
  { id: 10, text: '我认为生活充满了乐趣和可能性，哪怕遇到困难，也相信明天会更好。', scorings: [{ dimension: 'extraversion', subDimension: 'E6', reverse: false }] },
  { id: 11, text: '我乐于组织活动、分配任务。', scorings: [{ dimension: 'extraversion', subDimension: 'E3', reverse: false }] },
  { id: 12, text: '我向往那种无拘无束、随心所欲的生活，不用考虑后果。', scorings: [{ dimension: 'extraversion', subDimension: 'E5', reverse: false }] },
  { id: 13, text: '我很少生气，哪怕遇到烦心事，心情也能很快平复。', scorings: [{ dimension: 'neuroticism', subDimension: 'N2', reverse: true }] },
  { id: 14, text: '我经常行动快于思考，想到什么就做什么。', scorings: [{ dimension: 'neuroticism', subDimension: 'N5', reverse: false }] },
  { id: 15, text: '我在情绪激动时会忍不住骂人，用脏话发泄心中的不满。', scorings: [{ dimension: 'agreeableness', subDimension: 'A4', reverse: true }] },
  { id: 16, text: '如果有人惹恼了我，我会从暗处出手阻挠他的计划。', scorings: [{ dimension: 'agreeableness', subDimension: 'A2', reverse: true }] },
  { id: 17, text: '我在安排事项、处理事项上感觉游刃有余，很少会因为有事搞不定而抓狂。', scorings: [{ dimension: 'conscientiousness', subDimension: 'C1', reverse: false }] },
  { id: 18, text: '我在和人描述自己的时候，总是保持对自己的高评价，以至于有人觉得我是自傲的。', scorings: [{ dimension: 'agreeableness', subDimension: 'A5', reverse: true }] },
  { id: 19, text: '我的东西经常乱放，比如衣服随手扔在椅子上，书本堆满桌子。', scorings: [{ dimension: 'conscientiousness', subDimension: 'C2', reverse: true }] },
  { id: 20, text: '我总是避开人多的地方，宁愿待在家里，也不愿去凑热闹。', scorings: [{ dimension: 'extraversion', subDimension: 'E2', reverse: true }] },
  { id: 21, text: '我看到别人遇到困难时，我没什么感觉，因为这是他们的事，不是我的事。', scorings: [{ dimension: 'agreeableness', subDimension: 'A6', reverse: true }] },
  { id: 22, text: '我经常感到沮丧，提不起劲。', scorings: [{ dimension: 'neuroticism', subDimension: 'N3', reverse: false }] },
  { id: 23, text: '我总是担心事情会朝着最坏的方向发展，比如检测还没开始，就担心自己会发挥失常。', scorings: [{ dimension: 'neuroticism', subDimension: 'N1', reverse: false }] },
  { id: 24, text: '我经常高估自己的能力，比如接手一项任务时觉得自己肯定能搞定，结果发现并不简单。', scorings: [{ dimension: 'agreeableness', subDimension: 'A5', reverse: true }] },
  { id: 25, text: '我面对需要帮助的人，不会觉得同情也无意主动提供帮助。', scorings: [{ dimension: 'agreeableness', subDimension: 'A6', reverse: true }] },
  { id: 26, text: '我是全力以赴地完成手头的任务，哪怕已经很累，也要做到自己能力的极限。', scorings: [{ dimension: 'conscientiousness', subDimension: 'C4', reverse: false }] },
  { id: 27, text: '我会忍不住和别人炫耀自己的长处。', scorings: [{ dimension: 'agreeableness', subDimension: 'A5', reverse: true }] },
  { id: 28, text: '我喜欢任由思绪飘荡，喜欢在自己构建的幻想世界里，因为在那里一切皆有可能。', scorings: [{ dimension: 'openness', subDimension: 'O1', reverse: false }] },
  { id: 29, text: '我认为很多事情没有绝对的对错，只是立场不同，比如善恶往往不是黑白分明。', scorings: [{ dimension: 'openness', subDimension: 'O6', reverse: false }] },
  { id: 30, text: '我经常找不到东西，因为用完总是随手一放，下次要用就得翻箱倒柜。', scorings: [{ dimension: 'conscientiousness', subDimension: 'C2', reverse: true }] },
  { id: 31, text: '我习惯在行动前做好万全准备，比如旅行前查好路线，事情开始前整理方案。', scorings: [{ dimension: 'conscientiousness', subDimension: 'C6', reverse: false }] },
  { id: 32, text: '我清楚做事的正确方法，不会在细节上犯迷糊。', scorings: [{ dimension: 'conscientiousness', subDimension: 'C1', reverse: false }] },
  { id: 33, text: '我通常能克制自己的欲望，不会过度放纵，比如吃零食适可而止，玩游戏不会熬夜。', scorings: [{ dimension: 'neuroticism', subDimension: 'N5', reverse: true }] },
  { id: 34, text: '我被冒犯后，会记在心里，找机会报复回去。', scorings: [{ dimension: 'agreeableness', subDimension: 'A4', reverse: true }] },
  { id: 35, text: '我更喜欢按老一套的方法做事，觉得新方法不靠谱。', scorings: [{ dimension: 'openness', subDimension: 'O4', reverse: true }] },
  { id: 36, text: '我总想把开心的事第一时间告诉别人，比如刚看完一部好电影，就想拉着朋友安利。', scorings: [{ dimension: 'extraversion', subDimension: 'E1', reverse: false }] },
  { id: 37, text: '我会在吵架时侮辱对方，专挑难听的话刺伤别人。', scorings: [{ dimension: 'agreeableness', subDimension: 'A4', reverse: true }] },
  { id: 38, text: '我觉得抽象的理论很难理解，比如哲学、数学概念让人头疼。', scorings: [{ dimension: 'openness', subDimension: 'O5', reverse: true }] },
  { id: 39, text: '我对自己取得成果的能力有信心。', scorings: [{ dimension: 'conscientiousness', subDimension: 'C1', reverse: false }] },
  { id: 40, text: '我觉得在自己的幻想世界里很快乐。', scorings: [{ dimension: 'openness', subDimension: 'O1', reverse: false }] },
  { id: 41, text: '我讨厌被规则束缚，喜欢自由自在，想干嘛干嘛。', scorings: [{ dimension: 'extraversion', subDimension: 'E5', reverse: false }] },
  { id: 42, text: '我享受冒险的感觉，尝试新事物、去未知的地方让我兴奋。', scorings: [{ dimension: 'extraversion', subDimension: 'E5', reverse: false }] },
  { id: 43, text: '我倾向于认为别人的出发点都是好的，哪怕感到被冒犯了，也会考虑“他可能不是故意的”。', scorings: [{ dimension: 'agreeableness', subDimension: 'A1', reverse: false }] },
  { id: 44, text: '我认为对待罪犯，除了惩罚，更重要的是给予帮助和改造的机会。', scorings: [{ dimension: 'openness', subDimension: 'O6', reverse: false }] },
  { id: 45, text: '我在压力下能保持冷静，越紧张反而越镇定。', scorings: [{ dimension: 'neuroticism', subDimension: 'N6', reverse: true }] },
  { id: 46, text: '我很难相信别人，我认为别人接近我都是有目的的。', scorings: [{ dimension: 'agreeableness', subDimension: 'A1', reverse: true }] },
  { id: 47, text: '我经常打破规则，认为这世上很多规矩就是用来打破的。', scorings: [{ dimension: 'conscientiousness', subDimension: 'C3', reverse: true }] },
  { id: 48, text: '我在困难的社交场合，比如独自和重要人物交谈，也能保持镇定，不怯场。', scorings: [{ dimension: 'neuroticism', subDimension: 'N6', reverse: true }] },
  { id: 49, text: '我觉得主动与人攀谈、结交新朋友是件自然、简单的事，就像人生来就会呼吸一样。', scorings: [{ dimension: 'extraversion', subDimension: 'E1', reverse: false }] },
  { id: 50, text: '我会为了往上爬而使用一些欺骗的手段，比如必要的造假和抢夺功劳。', scorings: [{ dimension: 'agreeableness', subDimension: 'A2', reverse: true }] },
  { id: 51, text: '我经常看到别人遇到困难时，会忍不住伸出援手，比如帮老人拎东西，或者安慰哭泣的朋友。', scorings: [{ dimension: 'agreeableness', subDimension: 'A3', reverse: false }] },
  { id: 52, text: '我经常凭一时冲动做决定，比如心血来潮买下并不需要的东西。', scorings: [{ dimension: 'neuroticism', subDimension: 'N5', reverse: false }] },
  { id: 53, text: '我经常说话不算话，承诺的事转头就忘。', scorings: [{ dimension: 'conscientiousness', subDimension: 'C3', reverse: true }] },
  { id: 54, text: '我坚信人应该诚实，说话算话，谎言会让我感到极度不适。', scorings: [{ dimension: 'conscientiousness', subDimension: 'C3', reverse: false }] },
  { id: 55, text: '我对去陌生的地方旅行充满向往，崭新的见闻和体验令人兴奋。', scorings: [{ dimension: 'openness', subDimension: 'O4', reverse: false }] },
  { id: 56, text: '我喜欢各种热闹的聚会。', scorings: [{ dimension: 'extraversion', subDimension: 'E2', reverse: false }] },
  { id: 57, text: '我能很好地控制自己的欲望。', scorings: [{ dimension: 'neuroticism', subDimension: 'N5', reverse: true }] },
  { id: 58, text: '我常常会不喜欢自己。', scorings: [{ dimension: 'neuroticism', subDimension: 'N3', reverse: true }] },
  { id: 59, text: '我对自己整体感到满意，接受自己的优点和缺点。', scorings: [{ dimension: 'conscientiousness', subDimension: 'C1', reverse: false }] },
  { id: 60, text: '我曾经为了达成自己的目的，不动声色地利用过别人，就像下棋时把别人当作棋子一样。', scorings: [{ dimension: 'agreeableness', subDimension: 'A2', reverse: true }] },
  { id: 61, text: '我喜欢阅读那些能引起思考的书籍或文章，比如哲学随笔、科幻小说，或者深度的社会评论。', scorings: [{ dimension: 'openness', subDimension: 'O5', reverse: false }] },
  { id: 62, text: '我常常陷入一种挥之不去的低落情绪，心里仿佛压着一块石头。', scorings: [{ dimension: 'neuroticism', subDimension: 'N3', reverse: false }] },
  { id: 63, text: '我的生活节奏总是忙忙碌碌，日程表上填满了各种活动、事情，很少有闲着的时候。', scorings: [{ dimension: 'extraversion', subDimension: 'E4', reverse: false }] },
  { id: 64, text: '我的脾气来得很快，一点小事就能点燃我。', scorings: [{ dimension: 'neuroticism', subDimension: 'N2', reverse: false }] },
  { id: 65, text: '我害怕成为人群的焦点。', scorings: [{ dimension: 'neuroticism', subDimension: 'N4', reverse: false }] },
  { id: 66, text: '我喜欢什么都不做，享受无所事事的感觉。', scorings: [{ dimension: 'extraversion', subDimension: 'E4', reverse: true }] },
  { id: 67, text: '相比起独自一人，我更渴望融入群体，成为之中的一份子。', scorings: [{ dimension: 'extraversion', subDimension: 'E2', reverse: false }] },
  { id: 68, text: '我的房间经常很乱，东西堆得到处都是。', scorings: [{ dimension: 'conscientiousness', subDimension: 'C2', reverse: true }] },
  { id: 69, text: '我一旦制定了计划和目标，就能严格地执行下去。', scorings: [{ dimension: 'conscientiousness', subDimension: 'C5', reverse: false }] },
  { id: 70, text: '我闲不下来，一有空就会找点事做。', scorings: [{ dimension: 'extraversion', subDimension: 'E4', reverse: false }] },
  { id: 71, text: '我在学业上觉得“及格万岁”/在事业上觉得“看得过去就行了”/在人生目标上觉得“差不多就可以”，不愿多花精力追求更好。', scorings: [{ dimension: 'conscientiousness', subDimension: 'C4', reverse: true }] },
  { id: 72, text: '我容易感到恐慌，有时是有原因的，有时我也说不上原因。', scorings: [{ dimension: 'neuroticism', subDimension: 'N6', reverse: false }] },
  { id: 73, text: '我本能地讨厌与陌生人有身体接触，比如拥挤的地铁会让找浑身不自在。', scorings: [{ dimension: 'extraversion', subDimension: 'E2', reverse: true }] },
  { id: 74, text: '我习惯把物品归置得整整齐齐，家里的每样东西都有它的固定位置。', scorings: [{ dimension: 'conscientiousness', subDimension: 'C2', reverse: false }] },
  { id: 75, text: '我在聚会中喜欢穿梭在不同的小圈子之间，和每个人都聊上几句。', scorings: [{ dimension: 'extraversion', subDimension: 'E2', reverse: false }] },
  { id: 76, text: '我时常会放纵自己去做让自己感到快乐、兴奋或刺激的事，比如熬夜追剧到天亮，或者一口气吃完一整盒巧克力。', scorings: [{ dimension: 'neuroticism', subDimension: 'N5', reverse: false }] },
  { id: 77, text: '我看到比自己更痛苦、穷困的人，心里会感到难过，想为他们做点什么。', scorings: [{ dimension: 'agreeableness', subDimension: 'A6', reverse: false }] },
  { id: 78, text: '我很容易感到愤怒，就像一点就着的火药桶。', scorings: [{ dimension: 'neuroticism', subDimension: 'N2', reverse: false }] },
  { id: 79, text: '我很容易紧张，哪怕是一件小事，也会让我心跳加速、手心出汗。', scorings: [{ dimension: 'neuroticism', subDimension: 'N1', reverse: false }] },
  { id: 80, text: '我发自内心地愿意帮助别人，把别人的事当成自己的事。', scorings: [{ dimension: 'agreeableness', subDimension: 'A3', reverse: false }] },
  { id: 81, text: '我倾向于相信陌生人释放的善意。', scorings: [{ dimension: 'agreeableness', subDimension: 'A1', reverse: false }] },
  { id: 82, text: '我曾经把别人当作工具，用完就丢，为了自己的利益，我可以牺牲他人。', scorings: [{ dimension: 'agreeableness', subDimension: 'A2', reverse: true }] },
  { id: 83, text: '我不想在别人身上花时间，因为我的时间和精力很宝贵。', scorings: [{ dimension: 'agreeableness', subDimension: 'A3', reverse: true }] },
  { id: 84, text: '我喜欢一个人静静地思考自己感兴趣的问题。', scorings: [{ dimension: 'openness', subDimension: 'O5', reverse: false }] },
  { id: 85, text: '我觉得逛艺术馆、博物馆是一种折磨。', scorings: [{ dimension: 'openness', subDimension: 'O2', reverse: true }] },
  { id: 86, text: '我经常忽略自己的情绪，有时候别人问“你怎么了”，我自己都没意识到。', scorings: [{ dimension: 'openness', subDimension: 'O3', reverse: true }] },
  { id: 87, text: '我很难体会别人的情绪，别人难过，我很难感同身受。', scorings: [{ dimension: 'agreeableness', subDimension: 'A6', reverse: true }] },
  { id: 88, text: '我觉得国家对罪犯太仁慈了，应该更严厉惩罚。', scorings: [{ dimension: 'openness', subDimension: 'O6', reverse: true }] },
  { id: 89, text: '我觉得诗歌这种东西很无聊，看不懂，也不想懂。', scorings: [{ dimension: 'openness', subDimension: 'O2', reverse: true }] },
  { id: 90, text: '我身处人群之中反而觉得自在，比如在热闹的商场或地铁里，有一种融入的安全感。', scorings: [{ dimension: 'extraversion', subDimension: 'E2', reverse: false }] },
  { id: 91, text: '我在自我提升上，打磨技能上不愿意花太多时间，觉得差不多就行了。', scorings: [{ dimension: 'conscientiousness', subDimension: 'C4', reverse: true }] },
  { id: 92, text: '我尽量避免参与理论性的讨论，觉得那些太虚，不如聊点实际的。', scorings: [{ dimension: 'openness', subDimension: 'O5', reverse: true }] },
  { id: 93, text: '我觉得自己能掌控很多事情，而不是被动地被命运推着走。', scorings: [{ dimension: 'extraversion', subDimension: 'E3', reverse: false }] },
  { id: 94, text: '我不太在意别人的感受，说话做事全凭自己高兴。', scorings: [{ dimension: 'agreeableness', subDimension: 'A3', reverse: true }] },
  { id: 95, text: '我认为对待学习或工作必须认真严谨，不能马虎。', scorings: [{ dimension: 'conscientiousness', subDimension: 'C4', reverse: false }] },
  { id: 96, text: '我总能敏锐地察觉到周围人的情绪变化，哪怕对方强装笑脸，也能看出背后的低落。', scorings: [{ dimension: 'agreeableness', subDimension: 'A6', reverse: false }] },
  { id: 97, text: '我认为国家花太多钱在艺术上了。', scorings: [{ dimension: 'openness', subDimension: 'O6', reverse: true }] },
  { id: 98, text: '我不喜欢生活中有很多变化。', scorings: [{ dimension: 'openness', subDimension: 'O4', reverse: true }] },
  { id: 99, text: '我经常沉浸在自己的想象里，比如给路上的行人编故事，或者想象自己是故事主角。', scorings: [{ dimension: 'openness', subDimension: 'O1', reverse: false }] },
  { id: 100, text: '我刻意和别人保持距离，不让自己陷入亲密关系，因为害怕受伤。', scorings: [{ dimension: 'neuroticism', subDimension: 'N4', reverse: false }] },
  { id: 101, text: '我认为艺术——无论是绘画、音乐还是文学——是生活中不可或缺的一部分，看到美丽的作品会内心震颤。', scorings: [{ dimension: 'openness', subDimension: 'O2', reverse: true }] },
  { id: 102, text: '我常常在心里觉得自己比周围的大多数人都要优秀，哪怕嘴上不说。', scorings: [{ dimension: 'agreeableness', subDimension: 'A5', reverse: true }] },
  { id: 103, text: '我热爱那种肾上腺素飙升的感觉，比如坐过山车、看恐怖片，或者参与极限运动。', scorings: [{ dimension: 'extraversion', subDimension: 'E5', reverse: false }] },
  { id: 104, text: '我有时会脑子一热就采取行动，事后才后悔没多想想。', scorings: [{ dimension: 'neuroticism', subDimension: 'N5', reverse: false }] },
  { id: 105, text: '我愿意在关键时刻站出来，成为那个拿主意、担责任的人。', scorings: [{ dimension: 'extraversion', subDimension: 'E3', reverse: false }] },
  { id: 106, text: '我的脑海里经常上演各种天马行空的剧情，哪怕盯着天花板，也能编出一部奇幻史诗。', scorings: [{ dimension: 'openness', subDimension: 'O1', reverse: false }] },
  { id: 107, text: '我一旦许下承诺，就会尽力去兑现，哪怕只是随口说的一句“下次请你吃饭”。', scorings: [{ dimension: 'conscientiousness', subDimension: 'C3', reverse: false }] },
  { id: 108, text: '我在压力下容易崩溃。', scorings: [{ dimension: 'neuroticism', subDimension: 'N6', reverse: false }] },
  { id: 109, text: '我经常因为小事而感到恼火，比如手机卡顿、被人打断说话，都可能会让我有脾气。', scorings: [{ dimension: 'neuroticism', subDimension: 'N2', reverse: false }] },
  { id: 110, text: '我倾向于相信别人说的话，哪怕是和陌生人聊起，也会认真倾听、思考他所说的内容。', scorings: [{ dimension: 'agreeableness', subDimension: 'A1', reverse: false }] },
  { id: 111, text: '我发自内心地热爱生活，经常过得兴致勃勃。', scorings: [{ dimension: 'extraversion', subDimension: 'E6', reverse: false }] },
  { id: 112, text: '我容易和人发生肢体冲突，当被冒犯时，肢体动作可能来得比语言更快。', scorings: [{ dimension: 'agreeableness', subDimension: 'A4', reverse: true }] },
  { id: 113, text: '我只有在熟人身边才能放松，陌生环境会让我紧张不安。', scorings: [{ dimension: 'extraversion', subDimension: 'E2', reverse: true }] },
  { id: 114, text: '我面对诱惑时，能很好地克制自己。', scorings: [{ dimension: 'neuroticism', subDimension: 'N5', reverse: true }] },
  { id: 115, text: '我总能敏锐地察觉到自己内心的情绪波动，哪怕是一丝不易察觉的烦躁，也能捕捉到。', scorings: [{ dimension: 'openness', subDimension: 'O3', reverse: false }] },
  { id: 116, text: '我通常反应比别人慢半拍，比如别人讲了个笑话，我要过几秒才笑出来。', scorings: [{ dimension: 'extraversion', subDimension: 'E4', reverse: true }] },
  { id: 117, text: '我经常做事仓促，不考虑后果，先做了再说。', scorings: [{ dimension: 'neuroticism', subDimension: 'N5', reverse: false }] },
  { id: 118, text: '我看到街头的流浪者，心里会涌起一股酸涩的同情，哪怕只是匆匆一瞥。', scorings: [{ dimension: 'agreeableness', subDimension: 'A6', reverse: false }] },
];
